name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
        env:
          QUIT_ON_SYNTH_CHECKS: "0"

      - name: Build GDS
        uses: rowanG077/tt-gds-action@tt07-update-yosys
        env:
          QUIT_ON_SYNTH_CHECKS: "0"
          RUN_VERILATOR: "0"

  precheck:
    needs: gds
    runs-on: ubuntu-latest
    steps:
      - name: Run Tiny Tapeout Precheck
        uses: rowanG077/tt-gds-action/precheck@tt07-update-yosys
        env:
          QUIT_ON_SYNTH_CHECKS: "0"
          RUN_VERILATOR: "0"

  gl_test:
    needs: gds
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
        env:
          QUIT_ON_SYNTH_CHECKS: "0"
          RUN_VERILATOR: "0"

      - name: GL test
        uses: rowanG077/tt-gds-action/gl_test@tt07-update-yosys
        env:
          QUIT_ON_SYNTH_CHECKS: "0"
          RUN_VERILATOR: "0"

  viewer:
    needs: gds
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - uses: rowanG077/tt-gds-action/viewer@tt07-update-yosys
